### PR TITLE
Adding useMeta hook

### PR DESCRIPTION
**Pull request by soub4i**

### CODE REVIEW

**Comment by soub4i** [comment]
@stevenpersia this can be Added ?

**Review by webbertakken — CHANGES_REQUESTED** [review]
Lots of excess spaces and newlines introduced in this one.

Suggest not editing codeblocks from other hooks/readme.

**Comment by soub4i** [comment]
@webbertakken Thank you for the feedback yes I noticed there is a lot of unneeded new lines I will work on this

**Comment by soub4i** [comment]
Can you give this a try please @webbertakken

**Comment by stevenpersia** [comment]
There is multiple issues in your last commit : content from merge conflict system.

Sorry, I can't merge your PR. Feel free to open a new one 👍

**Pull request closed without merging**
